routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Kwaadpepper\CrudPolicies\Http\Controllers\AssetsController;
use Kwaadpepper\CrudPolicies\Http\Controllers\ModelsController;

$middlewareMinimal = [
    \Illuminate\Routing\Middleware\SubstituteBindings::class
];

Route::group([
    'as' => 'crud-policies.httpFileSend.',
    'middleware' => array_merge(['throttle:60,1'], $middlewareMinimal),
    'namespace' => 'Kwaadpepper\CrudPolicies\Http\Controllers'
], function () {
    $routePrefix = config('crud-policies.urlPrefix');

    // Assets
    Route::get(\sprintf('%s/{type}/{fileUri}', config('crud-policies.assetPath')), [AssetsController::class, 'asset'])
        ->where('type', '(js|css)')
        ->where('fileUri', '.*')
        ->name('asset')
        ->prefix($routePrefix);
});

Route::group([
    'as' => 'crud-policies.models.',
    'middleware' => array_merge(['throttle:250,1'], $middlewareMinimal),
    'namespace' => 'Kwaadpepper\CrudPolicies\Http\Controllers'
], function () {
    $routePrefix = config('crud-policies.urlPrefix');

    // Order change
    Route::put('{modelTable}/{modelId}/{colName}/{newOrder}/{oldUrl}', [ModelsController::class, 'changeOrder'])
        ->where('modelTable', '[a-z_]*')
        ->where('modelId', '[0-9]*')
        ->where('colName', '[a-zA-Z0-9_]*')
        ->where('newOrder', '[0-9]*')
        ->name('changeOrder')
        ->prefix($routePrefix);
});

resources/views/crud/create.blade.php
@extends($viewLayout)

@section('title', sprintf('%s - %s', transFb(sprintf('models.classes.%s', strtolower(Str::plural(class_basename($modelClass)))), Str::plural(class_basename($modelClass))), __('crud-policies::crud.create')))
@section('description', sprintf('%s %s', __('crud-policies::crud.create'), class_basename($modelClass)))
@section('metaIndex', 'noindex,nofollow')

@section('content')
<div class="card">
    @include('crud-policies::crud.modules.flashMessage')
    <div class="card-header">
        @include('crud-policies::crud.modules.breadcrumb', ['action' => CrudAction::create()])
        @include('crud-policies::crud.modules.actionbar.bar', ['action' => CrudAction::create()])
    </div>
    <div class="card-body">
        <form action="{{ CrudController::getRoutePrefixed("$modelTable.store") }}" method="POST" @if($hasFile) enctype="multipart/form-data" @endif>
            @csrf
            <table class="table table-sm table-bordered border-primary align-middle table-striped text-center">
                <thead class="thead-dark">
                <tr>
                    <th scope="col" class="w-25">{{ __('crud-policies::crud.property') }}</th>
                    <th scope="col" class="w-75">{{ __('crud-policies::crud.value') }}</th>
                </tr>
                </thead>
                <tbody>
                    @foreach ($modelClass::getEditableProperties() as $fieldName => $prop)
                    @php
                        // create form cannot accept readonly field
                        $prop['readonly'] = false;
                    @endphp
                    @if(in_array(CrudAction::create(), $prop['actions']))
                    <tr>
                    @include('crud-policies::crud.formfield')
                    </tr>
                    @endif
                    @endforeach
                </tbody>
            </table>
            <div class="col text-center">
                <button class="btn btn-info" type="submit">{{ __('crud-policies::crud.create') }}</button>
            </div>
        </form>
    </div>
</div>
@include('crud-policies::crud.modules.scriptConstants')
@endsection

resources/views/crud/edit.blade.php
@extends($viewLayout)

@section('title', sprintf('%s - %s', transFb(sprintf('models.classes.%s', strtolower(Str::plural(class_basename($modelClass)))), Str::plural(class_basename($modelClass))), __('crud-policies::crud.edit')))
@section('description', sprintf('%s %s', __('crud-policies::crud.edit'), trans(class_basename($modelClass))))
@section('metaIndex', 'noindex,nofollow')

@section('content')
<div class="card">
    @include('crud-policies::crud.modules.flashMessage')
    <div class="card-header">
        @include('crud-policies::crud.modules.breadcrumb', ['action' => CrudAction::update()])
        @include('crud-policies::crud.modules.actionbar.bar', ['action' => CrudAction::update()])
    </div>
    <div class="card-body">
        <form action="{{ CrudController::getRoutePrefixed("$modelTable.update", $model) }}" method="POST" @if($hasFile) enctype="multipart/form-data" @endif>
            @method('put')
            @csrf
            <table class="table table-sm table-bordered border-primary align-middle table-striped text-center">
                <thead class="thead-dark">
                <tr>
                    <th scope="col" class="w-25">{{ __('crud-policies::crud.property') }}</th>
                    <th scope="col" class="w-75">{{ __('crud-policies::crud.value') }}</th>
                </tr>
                </thead>
                <tbody>
                    @foreach ($modelClass::getEditableProperties() as $fieldName => $prop)
                    @if(in_array(CrudAction::update(), $prop['actions']))
                    <tr>
                    @include('crud-policies::crud.formfield')
                    </tr>
                    @endif
                    @endforeach
                </tbody>
            </table>
            <div class="col text-center">
                <button class="btn btn-info" type="submit">{{ __('crud-policies::crud.update') }}</button>
            </div>
        </form>
    </div>
</div>
@include('crud-policies::crud.modules.scriptConstants')
@endsection

resources/views/crud/formfield.blade.php
@php
$readonly = is_callable($prop['readonly']) ? $prop['readonly']() : $prop['readonly'];
@endphp
@switch($prop['type'])
    @case(CrudType::password())
    @include('crud-policies::crud.formfields.password')
    @break
    @case(CrudType::boolean())
    @include('crud-policies::crud.formfields.boolean')
    @break
    @case(CrudType::int())
    @include('crud-policies::crud.formfields.int')
    @break
    @case(CrudType::float())
    @include('crud-policies::crud.formfields.float')
    @break
    @case(CrudType::unsignedint())
    @include('crud-policies::crud.formfields.int', ['unsigned' => true])
    @break
    @case(CrudType::unsignedfloat())
    @include('crud-policies::crud.formfields.float', ['unsigned' => true])
    @break
    @case(CrudType::email())
    @include('crud-policies::crud.formfields.email')
    @break
    @case(CrudType::text())
    @include('crud-policies::crud.formfields.text')
    @break
    @case(CrudType::json())
    @include('crud-policies::crud.formfields.json')
    @break
    @case(CrudType::image())
    @include('crud-policies::crud.formfields.image')
    @break
    @case(CrudType::file())
    @include('crud-policies::crud.formfields.file')
    @break
    @case(CrudType::enum())
    @include('crud-policies::crud.formfields.enum')
    @break
    @case(CrudType::order())
    @include('crud-policies::crud.formfields.order')
    @break
    @case(CrudType::color())
    @include('crud-policies::crud.formfields.color')
    @break
    @case(CrudType::belongsTo())
    @include('crud-policies::crud.formfields.belongsTo')
    @break
    @case(CrudType::belongsToMany())
    @include('crud-policies::crud.formfields.belongsToMany')
    @break
    @case(CrudType::string())
    @default
    @include('crud-policies::crud.formfields.string')
@endswitch

resources/views/crud/formfields/belongsTo.blade.php
@php
    $related = isset($model) ? $props[$fieldName]['belongsTo']::find($model->{$fieldName}) : null;
    if($related) {
        $related = [
            'label' => $related->crudLabel,
            'value' => $related->crudValue
        ];
    }
@endphp
<td>
    <label class="form-label">{{ $prop['label'] }}</label>
</td>
<td>
    <belongs-to
        readonly="{{ $readonly }}"
        tablename="{{ $modelTable }}"
        name="{{ $fieldName }}"
        db-value='@json($related)'>
    </belongs-to>
</td>

@push('scriptsConstants')
<script>
    if (!window.__CRUD) {
        window.__CRUD = {};
    }
    if(!window.__CRUD._routes) {
        window.__CRUD._routes = {};
    }
    window.__CRUD._routes['{{$modelTable}}.{{$fieldName}}.model.index'] = '{{ CrudController::getRoutePrefixed((new $props[$fieldName]['belongsTo'])->getTable().'.index') }}';
</script>
@endpush

resources/views/crud/formfields/belongsToMany.blade.php
@php
    $related = isset($model) ? $model->{$fieldName}->mapWithKeys(function ($model) use($prop) {
        return [$model->{'id'} => [
            'label' => $model->{$prop['belongsToManyLabel']},
            'value' => $model->{'id'}
        ]];
    }) : [];
@endphp
<td>
    <label class="form-label">{{ $prop['label'] }}</label>
</td>
<td>
    <belongs-to-many
        readonly="{{ $readonly }}"
        tablename="{{ $modelTable }}"
        name="{{ $fieldName }}"
        db-value='@json($related)'>
    </belongs-to-many>
</td>

@push('scriptsConstants')
<script>
    if (!window.__CRUD) {
        window.__CRUD = {};
    }
    if(!window.__CRUD._routes) {
        window.__CRUD._routes = {};
    }
    window.__CRUD._routes['{{$modelTable}}.{{$fieldName}}.model.index'] = '{{ CrudController::getRoutePrefixed((new $props[$fieldName]['belongsToMany'])->getTable().'.index') }}';
</script>
@endpush

resources/views/crud/formfields/boolean.blade.php
<td>
    <label for="{{ $fieldName }}" class="form-label">{{ $prop['label'] }}</label>
</td>
<td>
    <label for="{{ $fieldName }}" class="row">
        <div class="col">
            <div class="form-check form-switch ms-2">
                <input
                    id="{{ $fieldName }}"
                    name="{{ $fieldName }}"
                    type="checkbox"
                    class="ml-2 form-check-input"
                    value="1"
                    @if(old($fieldName) ?? ((isset($model) and $model->{$fieldName}) ? $model->{$fieldName} : $prop['default'] ?? false))checked @endif
                    @if($prop['disabled'])disabled @endif
                    @if($readonly)readonly @endif>
            </div>
        </div>
    </label>
</td>

resources/views/crud/formfields/color.blade.php
<td>
    <label for="{{ $fieldName }}" class="form-label">{{ $prop['label'] }}</label>
</td>
<td>
    @if(strlen($prop['placeholder']))
    <div class="form-floating">
        <input
            id="{{ $fieldName }}"
            name="{{ $fieldName }}"
            type="text"
            data-jscolor=""
            class="form-control"
            value="{{ old($fieldName) ?? $model->{$fieldName} ?? $prop['default'] ?? '' }}"
            @if($prop['disabled'])disabled @endif
            @if($readonly)readonly @endif
            @if($prop['required'] or (!$prop['required'] and !$prop['nullable']))required @endif>
        <label for="{{ $fieldName }}" class="form-label">{{ __('ex: :placeholder', ['placeholder' => $prop['placeholder']]) }}</label>
    </div>
    @else
    <input
        id="{{ $fieldName }}"
        name="{{ $fieldName }}"
        type="text"
        data-jscolor=""
        class="form-control"
        value="{{ old($fieldName) ?? $model->{$fieldName} ?? $prop['default'] ?? '' }}"
        @if($prop['disabled'])disabled @endif
        @if($readonly)readonly @endif
        @if($prop['required'] or (!$prop['required'] and !$prop['nullable']))required @endif>
    @endif
</td>
@include('crud-policies::crud.modules.color')

resources/views/crud/formfields/email.blade.php
<td>
    <label for="{{ $fieldName }}" class="form-label">{{ $prop['label'] }}</label>
</td>
<td>
    @if(strlen($prop['placeholder']))
    <div class="form-floating">
        <input
            id="{{ $fieldName }}"
            name="{{ $fieldName }}"
            type="email"
            class="form-control"
            value="{{ old($fieldName) ?? $model->{$fieldName} ?? $prop['default'] ?? '' }}"
            @if(isset($prop['rules']['max']))maxlength="{{ $prop['rules']['max'] }}"@endif
            @if(isset($prop['rules']['min']))minlength="{{ $prop['rules']['min'] }}"@endif
            @if($prop['disabled'])disabled @endif
            @if($readonly)readonly @endif
            @if($prop['required'] or (!$prop['required'] and !$prop['nullable']))required @endif>
        <label for="{{ $fieldName }}" class="form-label">{{ __('ex: :placeholder', ['placeholder' => $prop['placeholder']]) }}</label>
    </div>
    @else
    <input
        id="{{ $fieldName }}"
        name="{{ $fieldName }}"
        type="email"
        class="form-control"
        value="{{ old($fieldName) ?? $model->{$fieldName} ?? $prop['default'] ?? '' }}"
        @if(isset($prop['rules']['max']))maxlength="{{ $prop['rules']['max'] }}"@endif
        @if(isset($prop['rules']['min']))minlength="{{ $prop['rules']['min'] }}"@endif
        @if($prop['disabled'])disabled @endif
        @if($readonly)readonly @endif
        @if($prop['required'] or (!$prop['required'] and !$prop['nullable']))required @endif>
    @endif
</td>

resources/views/crud/formfields/enum.blade.php
<td>
    <label for="{{ $fieldName }}" class="form-label">{{ $prop['label'] }}</label>
</td>
<td>
    <select id="{{ $fieldName }}" class="form-control" name="{{ $fieldName }}" @if($readonly) readonly @endif @if($prop['disabled']) disabled @endif>
        {{-- TODO handle enum nullable ? --}}
        {{-- @if($prop['nullable'])
        @endif --}}
        @foreach ($prop['enum']::toArray() as $enum)
            <option value="{{$enum->value}}" @if(isset($model) and $enum->equals($model->{$fieldName}))selected @endif>{{__($enum->label)}}</option>
        @endforeach
    </select>
</td>

resources/views/crud/formfields/file.blade.php
<td>
    <label for="{{ $fieldName }}" class="form-label">{{ $prop['label'] }}</label>
</td>
<td>
    @if(strlen($prop['placeholder']))
    <div class="form-floating">
    @endif
        <input
            id="{{ $fieldName }}"
            name="{{ $fieldName }}"
            type="file"
            class="form-control"
            value="{{ old($fieldName) ?? $model->{$fieldName} ?? $prop['default'] ?? '' }}"
            @if($prop['accept'])accept="{{ $prop['accept'] }}" @endif
            @if($prop['disabled'])disabled @endif
            @if($readonly)readonly @endif
            @if(($prop['required'] or (!$prop['required'] and !$prop['nullable'])) and !(isset($model) and $model->{$fieldName}))required @endif>
    @if(strlen($prop['placeholder']))
        <label for="{{ $fieldName }}" class="form-label">{{ __('ex: :placeholder', ['placeholder' => $prop['placeholder']]) }}</label>
    </div>
    @endif
    @if(isset($model) and $model->{$fieldName})
    <img class="img-responsive" src="{{ sprintf('/storage/%s', $model->{$fieldName}) }}" alt="{{ sprintf('/storage/%s', $model->{$fieldName}) }}">
    @endif
</td>

resources/views/crud/formfields/image.blade.php
<td>
    <label for="{{ $fieldName }}" class="form-label">{{ $prop['label'] }}</label>
</td>
<td>
    @if(strlen($prop['placeholder']))
    <div class="form-floating">
    @endif
        <input
            id="{{ $fieldName }}"
            name="{{ $fieldName }}"
            type="file"
            class="form-control"
            value="{{ old($fieldName) ?? $model->{$fieldName} ?? $prop['default'] ?? '' }}"
            @if($prop['disabled'])disabled @endif
            @if($readonly)readonly @endif
            @if(($prop['required'] or (!$prop['required'] and !$prop['nullable'])) and !(isset($model) and $model->{$fieldName}))required @endif>
    @if(strlen($prop['placeholder']))
        <label for="{{ $fieldName }}" class="form-label">{{ __('ex: :placeholder', ['placeholder' => $prop['placeholder']]) }}</label>
    </div>
    @endif
    @if(isset($model) and $model->{$fieldName})
    <img class="img-fluid" src="{{ sprintf('/storage/%s', $model->{$fieldName}) }}" alt="{{ sprintf('/storage/%s', $model->{$fieldName}) }}">
    @endif
</td>

resources/views/crud/formfields/int.blade.php
<td>
    <label for="{{ $fieldName }}" class="form-label">{{ $prop['label'] }}</label>
</td>
<td>
    <input
        id="{{ $fieldName }}"
        class="form-control"
        name="{{ $fieldName }}"
        type="number"
        placeholder="{{ $prop['placeholder'] }}"
        @if(isset($unsigned))
        min="0"
        @endif
        value="{{ old($fieldName) ?? $model->{$fieldName} ?? $prop['rules']['min'] ?? $prop['default'] ?? 0 }}"
        @if(isset($prop['rules']['max']))max="{{ $prop['rules']['max'] }}"@endif
        @if(isset($prop['rules']['min']))min="{{ $prop['rules']['min'] }}"@endif
        @if(isset($prop['rules']['step']))step="{{ $prop['rules']['step'] }}"@endif
        @if($prop['disabled'])disabled @endif
        @if($readonly)readonly @endif
        @if($prop['required'] or (!$prop['required'] and !$prop['nullable']))required @endif>
</td>

resources/views/crud/formfields/json.blade.php
@php
$jsonValue = old($fieldName) ?? (
    (isset($model) and $model->{$fieldName}) ?
    (
        is_array($model->{$fieldName}) ?
        json_encode($model->{$fieldName}) : $model->{$fieldName}
    ) : $prop['default']
);
@endphp
<td>
    <label for="{{ $fieldName }}" class="form-label">{{ $prop['label'] }}</label>
</td>
<td>
    <div class="mb-3">
        <div id="{{ $fieldName }}jsoneditor"></div>
        <textarea id="{{ $fieldName }}" name="{{ $fieldName }}" rows="3" class="form-control d-none" @if($readonly) readonly @endif>{!! $jsonValue !!}</textarea>
    </div>
</td>
@include('crud-policies::crud.modules.jsoneditor', [
    'fieldName' => $fieldName,
    'value' => $jsonValue,
    'prop' => $prop
])

resources/views/crud/layout.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <title>{{ config('app.name') }}@hasSection('title') - @yield('title')@endif</title>
        <meta charset="utf-8">
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta name="description" content="@yield('description')">
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <meta name="robots" content="index, follow">
        <link rel="canonical" href="{{ url()->current() }}" />

        <!-- STYLES -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" integrity="sha256-hHKA3d/HttC8OW3Sl093W8DoZudhHJDj++kZYo6MLzA=" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11.0.16/dist/sweetalert2.min.css" integrity="sha256-qpXwccFYncH5gTqXFe9EXZ8QeDw1Re68bbNVfFZzIzg=" crossorigin="anonymous">
        <link rel="stylesheet" href="{{ route('crud-policies.httpFileSend.asset', [
            'type' => 'css',
            'fileUri' => 'crud.css'
        ]) }}">

        @stack('styles')
    </head>
    <body>
        <div id="app">
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
                <div class="container-fluid">
                    <a class="navbar-brand" href="/">{{ config('app.name') }}</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarScroll">
                        <ul class="navbar-nav ms-auto my-2 my-lg-0 navbar-nav-scroll " style="--bs-scroll-height: 100px;">
                            @auth()
                            <li class="nav-item"><span class="nav-link text-success">{{ auth()->user()->name }}</span></li>
                            @endauth
                        </ul>
                    </div>
                </div>
            </nav>
            <div class="container-fluid">
                <div class="row">
                    @if(isset($modelsClasses))
                    <nav id="sidebarMenu" class="col-md-3 col-lg-2 min-height-100vh d-md-block bg-light sidebar collapse">
                        <div class="sidebar-sticky pt-3 d-flex flex-column justify-content-between align-items-center">
                            <div class="col-12 mt-4">
                                @foreach($modelsClasses as $crudModel)
                                @if(
                                    auth()->user()->can('viewAny', $crudModel) or
                                    auth()->user()->can('create', $crudModel)
                                )
                                <h6 class="sidebar-heading px-3 mb-1 text-muted">
                                    <span>{{ __(ucfirst(collect(explode('\\', $crudModel))->last())) }}</span>
                                </h6>
                                @php
                                $crudModel = new $crudModel();
                                @endphp
                                <ul class="nav flex-column mb-2">
                                    @can('viewAny', $crudModel)
                                    <li class="nav-item"><a class="nav-link" href="{{ CrudController::getRoutePrefixed(sprintf('%s.index', $crudModel->getTable())) }}">{{ __('crud-policies::crud.viewAny') }}</a></li>
                                    @endcan
                                    @can('create', $crudModel)
                                    <li class="nav-item"><a class="nav-link" href="{{ CrudController::getRoutePrefixed(sprintf('%s.create', $crudModel->getTable())) }}">{{ __('crud-policies::crud.create') }}</a></li>
                                    @endcan
                                </ul>
                                <hr>
                                @endcan
                                @endforeach
                            </div>
                        </div>
                    </nav>

                    <main role="main" class="col-md-9 mt-5 mb-5 ml-sm-auto col-lg-10 px-md-4">
                    @else
                    <main role="main" class="mt-5 mb-5">
                    @endif
                        @yield('content')
                    </main>
                </div>
            </div>
        </div>
        @stack('scriptsConstants')
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha256-edRDsV9ULIqKzKjpN/KjyQ7Lp4vUn9usbJuHjH8Sk+k=" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.0.16/dist/sweetalert2.all.min.js" integrity="sha256-551HBsteMvKOSqjUXSmRy/EOF0bBNbWB96b5L3Deh8A=" crossorigin="anonymous"></script>
        <script src="//cdn.jsdelivr.net/npm/sweetalert2@10"></script>
        <script src="{{ route('crud-policies.httpFileSend.asset', [
            'type' => 'js',
            'fileUri' => 'crud.js'
        ]) }}"></script>
        @stack('scripts')
    </body>
</html>

resources/views/crud/printfield.blade.php
@switch($action)
    @case(CrudAction::viewAny())
        @switch($props['type'])
            @case(CrudType::email())
                <a href="mailto:$field">{{ $field }}</a>
                @break
            @case(CrudType::enum())
                {{ $model->{$fieldName}->label }}
                @break
            @case(CrudType::belongsTo())
            @php
                $obj = null;
                $obj = $model->{Str::singular((new $prop['belongsTo']())->getTable())} ??
                    $prop['belongsTo']::find($model->{$fieldName});
            @endphp
                {{ $obj->{$model->crudLabelColumn} }}
                @break
            @case(CrudType::belongsToMany())
                {{ $model->{$fieldName}->implode($prop['belongsToManyLabel'], ',') }}
                @break
            @case(CrudType::boolean())
                @if($model->{$fieldName})OUI @else NON @endif
                @break
            @case(CrudType::image())
                <img class="img-fluid" src="{{ sprintf('/storage/%s', $model->{$fieldName}) }}" alt="{{ sprintf('/storage/%s', $model->{$fieldName}) }}">
                @break
            @case(CrudType::file())
                <a href="{{ sprintf('/storage/%s', $model->{$fieldName}) }}" target="_blank">{{ sprintf('/storage/%s', $model->{$fieldName}) }}</a>
                @break
            @case(CrudType::uri())
                <a href="{{ $model->{$fieldName} }}" target="_blank">{{ $model->{$fieldName} }}</a>
                @break
            @case(CrudType::order())
                @if(
                    Session::get("crud.$modelTable.sort_col") === $fieldName and
                    Session::get("crud.$modelTable.sort_way") === 'asc'
                )
                <span>
                    @if($model->{$fieldName} - 1 >= 0)
                    <form class="d-inline" action="{{ route('crud-policies.models.changeOrder', [
                        'modelTable' => $modelTable,
                        'modelId' => $model->id,
                        'colName' => $fieldName,
                        'newOrder' => $model->{$fieldName} - 1,
                        'oldUrl' => base64_encode(request()->getRequestUri())
                    ]) }}" method="POST">
                        @csrf
                        @method('put')
                        <button class="col_sort btn btn-xs btn-primary text-decoration-none fw-bold lead desc">↑</button>
                    </form>
                    &nbsp;
                    @else
                    <span class="ms-2 me-3">&nbsp;</span>
                    @endif
                    {{ $model->{$fieldName} }}
                    @if(${"$modelTable$fieldName"} !== $model->{$fieldName})
                    &nbsp;
                    <form class="d-inline" action="{{ route('crud-policies.models.changeOrder', [
                        'modelTable' => $modelTable,
                        'modelId' => $model->id,
                        'colName' => $fieldName,
                        'newOrder' => $model->{$fieldName} + 1,
                        'oldUrl' => base64_encode(request()->getRequestUri())
                    ]) }}" method="POST">
                        @csrf
                        @method('put')
                        <button class="col_sort btn btn-xs btn-primary text-decoration-none fw-bold lead asc">↓</button>
                    </form>
                    @else
                    <span class="ms-2 me-3">&nbsp;</span>
                    @endif
                </span>
                @else
                {{ $model->{$fieldName} }}
                @endif
                @break
            @default
                {{ $field }}
        @endswitch
        @break

    @case(CrudAction::view())
        @switch($props['type'])
            @case(CrudType::email())
                <a href="mailto:$field">{{ $field }}</a>
                @break
            @case(CrudType::enum())
                {{ $model->{$fieldName}->label }}
                @break
            @case(CrudType::json())
                @json($field)
                @break
            @case(CrudType::boolean())
                @if($model->{$fieldName})OUI @else NON @endif
                @break
            @case(CrudType::image())
                <img class="img-fluid" src="{{ sprintf('/storage/%s', $model->{$fieldName}) }}" alt="{{ sprintf('/storage/%s', $model->{$fieldName}) }}">
                @break
            @case(CrudType::file())
                <a href="{{ sprintf('/storage/%s', $model->{$fieldName}) }}" target="_blank">{{ pathinfo($model->{$fieldName} ?? '', PATHINFO_BASENAME) }}</a>
                @break
            @case(CrudType::uri())
                <a href="{{ $model->{$fieldName} }}" target="_blank">{{ pathinfo($model->{$fieldName} ?? '', PATHINFO_BASENAME) }}</a>
                @break
            @case(CrudType::order())
                {{ $model->{$fieldName} }}
                @break
            @case(CrudType::belongsTo())
                {{ $prop['belongsTo']::find($model->{$fieldName})->{$model->crudLabelColumn} }}
                @break
            @case(CrudType::belongsToMany())
                {{ $model->{$fieldName}->implode($prop['belongsToManyLabel'], ',') }}
                @break
            @default
                {{ $field }}
        @endswitch
        @break

    @default
        @dd('unknown action')
@endswitch